### PR TITLE
TypeOrm example

### PR DESCRIPTION
**Pull request by muturgan**

### CODE REVIEW

**Comment by AlmogCohen** [comment]
hi repo maintainers....any chance super important PRs like this can be merged?

**Comment by AlmogCohen** [comment]
Actually, by now, this PR has to be updated to work with the new package names as mentioned here https://github.com/SoftwareBrothers/adminjs-nestjs/issues/28

(admin-bro --> adminjs, adminBro --> AdminJs)

**Comment by AlmogCohen** [comment]
and, when I try to use the example based on the repo name changes, I still get this error `TypeError: this.model.getRepository is not a function` 🤷 

not sure yet what is the source of the issue

**Comment by dziraf** [comment]
I can approve and merge if you rename `admin-bro`/`adminbro`, `AdminBro` occurrences to `adminjs` and `AdminJS` (and related packages)

**Comment by ariansobczak-rst** [comment]
NestJS integration is now available in new example app https://github.com/SoftwareBrothers/adminjs-example-app

**Pull request closed without merging**
